### ISSUE TITLE
Can't add labels using my preset

### ISSUE THREAD

**Issue by vincentaudebert** [codenameyau/github-label#32]
Hi,

I added my token to my bash_profile.
Then tried to run: `github-label 'springload/springtunes' labels.json`

I get this error:

```
/Users/VincentAudebert/.nvm/versions/node/v4.2.4/lib/node_modules/github-label/bin/github-label.js:88
    data.forEach(function(element) {
        ^

TypeError: Cannot read property 'forEach' of undefined
    at /Users/VincentAudebert/.nvm/versions/node/v4.2.4/lib/node_modules/github-label/bin/github-label.js:88:9
    at /Users/VincentAudebert/.nvm/versions/node/v4.2.4/lib/node_modules/github-label/bin/github-label.js:82:5
    at /Users/VincentAudebert/.nvm/versions/node/v4.2.4/lib/node_modules/github-label/src/client.js:42:5
    at /Users/VincentAudebert/.nvm/versions/node/v4.2.4/lib/node_modules/github-label/node_modules/octonode/lib/octonode/repo.js:303:18
    at Client.errorHandle (/Users/VincentAudebert/.nvm/versions/node/v4.2.4/lib/node_modules/github-label/node_modules/octonode/lib/octonode/client.js:181:16)
    at Request._callback (/Users/VincentAudebert/.nvm/versions/node/v4.2.4/lib/node_modules/github-label/node_modules/octonode/lib/octonode/client.js:197:24)
    at Request.self.callback (/Users/VincentAudebert/.nvm/versions/node/v4.2.4/lib/node_modules/github-label/node_modules/octonode/node_modules/request/request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/VincentAudebert/.nvm/versions/node/v4.2.4/lib/node_modules/github-label/node_modules/octonode/node_modules/request/request.js:1318:14)
```

My preset file contains this:

```
[
  {
    "name": "★★★",
    "color": "5319e7"
  },
  {
    "name": "★★☆",
    "color": "5319e7"
  },
  {
    "name": "★☆☆",
    "color": "5319e7"
  },
  {
    "name": "0 - Backlog",
    "color": "cccccc"
  },
  {
    "name": "1 - Ready",
    "color": "cccccc"
  },
  {
    "name": "2 - Working",
    "color": "cccccc"
  },
  {
    "name": "3 - To be tested",
    "color": "cccccc"
  },
  {
    "name": "4 - Testing",
    "color": "cccccc"
  },
  {
    "name": "5 - Tested",
    "color": "cccccc"
  },
  {
    "name": "6 - Live",
    "color": "cccccc"
  },
  {
    "name": "BED",
    "color": "0000CD"
  },
  {
    "name": "Big",
    "color": "A52A2A"
  },
  {
    "name": "Bug",
    "color": "fc2929"
  },
  {
    "name": "Content Update",
    "color": "ffb600"
  },
  {
    "name": "Design",
    "color": "fbca04"
  },
  {
    "name": "Duplicate",
    "color": "cccccc"
  },
  {
    "name": "Enhancement",
    "color": "84b6eb"
  },
  {
    "name": "FED",
    "color": "0e8a16"
  },
  {
    "name": "Future",
    "color": "ffffff"
  },
  {
    "name": "Help wanted",
    "color": "cc317c"
  },
  {
    "name": "Invalid",
    "color": "e6e6e6"
  },
  {
    "name": "Medium",
    "color": "F4A460"
  },
  {
    "name": "Feature name 1",
    "color": "1E90FF"
  },
  {
    "name": "Question",
    "color": "cc317c"
  },
  {
    "name": "Small",
    "color": "FFEC8B"
  },
  {
    "name": "Tested & Failed",
    "color": "e99695"
  },
  {
    "name": "Tested & Passed",
    "color": "c2e0c6"
  },
  {
    "name": "Won't fix",
    "color": "000000"
  }
]
```

**Comment by codenameyau** [comment]
Hi @vincentaudebert,

Try running the command with the -j flag like so

``` bash
github-label 'springload/springtunes' -j labels.json
```
