### ISSUE TITLE
Failure when updating label color

### ISSUE THREAD

**Issue by stkent** [codenameyau/github-label#33]
Initial invocation `github-label -j config.json stkent/redacted` worked fine.

<details>
  <summary>Initial config file</summary>

	[
		{
			"name": "type: bug",
			"color": "0052cc"
		},
		{
			"name": "type: clarification",
			"color": "009800"
		},
		{
			"name": "type: enhancement",
			"color": "009800"
		},
		{
			"name": "type: discussion",
			"color": "009800"
		},
		{
			"name": "status: awaiting triage",
			"color": "bfe5bf"
		},
		{
			"name": "size: small",
			"color": "bfe5bf"
		},
		{
			"name": "size: medium",
			"color": "bfe5bf"
		},
		{
			"name": "size: large",
			"color": "bfe5bf"
		},
		{
			"name": "enhancement status: accepted",
			"color": "dddddd"
		},
		{
			"name": "enhancement status: declined",
			"color": "e11d21"
		},
		{
			"name": "bug status: confirmed",
			"color": "dddddd"
		},
		{
			"name": "bug status: information needed",
			"color": "dddddd"
		},
		{
			"name": "bug status: unable to reproduce",
			"color": "dddddd"
		},
		{
			"name": "bug status: working as intended",
			"color": "dddddd"
		},
		{
			"name": "assignment status: available",
			"color": "eb6420"
		},
		{
			"name": "assignment status: reserved",
			"color": "fad8c7"
		},
		{
			"name": "development status: not started",
			"color": "dddddd"
		},
		{
			"name": "development status: in progress",
			"color": "dddddd"
		},
		{
			"name": "development status: needs review",
			"color": "dddddd"
		},
		{
			"name": "development status: in review",
			"color": "dddddd"
		},
		{
			"name": "development status: implemented",
			"color": "dddddd"
		},
		{
			"name": "development status: shipped",
			"color": "dddddd"
		},
		{
			"name": "blocked",
			"color": "fad8c7"
		},
		{
			"name": "duplicate",
			"color": "fad8c7"
		},
		{
			"name": "abandoned?",
			"color": "fad8c7"
		},
		{
			"name": "good first patch",
			"color": "fad8c7"
		}
	]
</details>

I then tweaked the color of a single label (`assignment status: available`):

<details>
<summary>Updated config file</summary>

	[
		{
			"name": "type: bug",
			"color": "0052cc"
		},
		{
			"name": "type: clarification",
			"color": "009800"
		},
		{
			"name": "type: enhancement",
			"color": "009800"
		},
		{
			"name": "type: discussion",
			"color": "009800"
		},
		{
			"name": "status: awaiting triage",
			"color": "bfe5bf"
		},
		{
			"name": "size: small",
			"color": "bfe5bf"
		},
		{
			"name": "size: medium",
			"color": "bfe5bf"
		},
		{
			"name": "size: large",
			"color": "bfe5bf"
		},
		{
			"name": "enhancement status: accepted",
			"color": "dddddd"
		},
		{
			"name": "enhancement status: declined",
			"color": "e11d21"
		},
		{
			"name": "bug status: confirmed",
			"color": "dddddd"
		},
		{
			"name": "bug status: information needed",
			"color": "dddddd"
		},
		{
			"name": "bug status: unable to reproduce",
			"color": "dddddd"
		},
		{
			"name": "bug status: working as intended",
			"color": "dddddd"
		},
		{
			"name": "assignment status: available",
			"color": "eb6440"
		},
		{
			"name": "assignment status: reserved",
			"color": "fad8c7"
		},
		{
			"name": "development status: not started",
			"color": "dddddd"
		},
		{
			"name": "development status: in progress",
			"color": "dddddd"
		},
		{
			"name": "development status: needs review",
			"color": "dddddd"
		},
		{
			"name": "development status: in review",
			"color": "dddddd"
		},
		{
			"name": "development status: implemented",
			"color": "dddddd"
		},
		{
			"name": "development status: shipped",
			"color": "dddddd"
		},
		{
			"name": "blocked",
			"color": "fad8c7"
		},
		{
			"name": "duplicate",
			"color": "fad8c7"
		},
		{
			"name": "abandoned?",
			"color": "fad8c7"
		},
		{
			"name": "good first patch",
			"color": "fad8c7"
		}
	]
</details>

 and invoked the same command. The tool terminated while updating that label with the following output:

```
[+] Updated label: "assignment status: available"
/usr/local/lib/node_modules/github-label/bin/github-label.js:124
      else if (data.color !== label.color) {
                   ^

TypeError: Cannot read property 'color' of undefined
    at /usr/local/lib/node_modules/github-label/bin/github-label.js:124:20
    at /usr/local/lib/node_modules/github-label/src/client.js:49:5
    at /usr/local/lib/node_modules/github-label/node_modules/octonode/lib/octonode/label.js:15:18
    at Request._callback (/usr/local/lib/node_modules/github-label/node_modules/octonode/lib/octonode/client.js:195:20)
    at self.callback (/usr/local/lib/node_modules/github-label/node_modules/request/request.js:373:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/github-label/node_modules/request/request.js:971:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
```

**Comment by stkent** [comment]
Re-running the script appears to have resulted in a success, so maybe this is just an obscure message around a network call that failed?

**Comment by codenameyau** [comment]
Most likely it was a network issue that occurred when trying to fetch your existing labels. 
- https://github.com/codenameyau/github-label/blob/master/src/client.js#L47-L50

If the issue occurs again, let me know and I can update the exception message.

This should be the expected output.

```bash
$ github-label -j progress.json codenameyau/github-label
[-] Skipped label: "progress: development"
[-] Skipped label: "progress: testing"
[-] Skipped label: "progress: design"
[-] Skipped label: "progress: release"
[-] Skipped label: "progress: blocked"
[-] Skipped label: "progress: backlog"
[-] Skipped label: "progress: review"
[-] Skipped label: "progress: standby"

$ ls
default.json  priority.json progress.json

$ vim progress.json 

$ github-label -j progress.json codenameyau/github-label
[-] Skipped label: "progress: development"
[-] Skipped label: "progress: testing"
[-] Skipped label: "progress: release"
[-] Skipped label: "progress: design"
[-] Skipped label: "progress: review"
[-] Skipped label: "progress: blocked"
[-] Skipped label: "progress: standby"
[+] Updated label: "progress: backlog"
```
